name: Versioning Control

on: 
    push:
      branches:
        - main
      paths-ignore:
        - 'CHANGELOG.md'
        - 'package.json'
        - 'package-lock.json'
    workflow_dispatch: # Evento que aciona o fluxo de trabalho manualmente
      inputs: # Define os inputs do fluxo de trabalho
        name: # Define o input "name"
          description: 'Trigger manual do Workflow' # Descrição do input

jobs: 
    versioning-control:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install and Build
              run: |
                npm install

            - name: Configuring Git Account
              run: |
                git config --global user.email "pipelines@toolboxdevops.cloud"
                git config --global user.name "Toolbox Automation"

            - name: Run Semantic Release 
              run: |
      
        env:
          # O semantic-release precisa deste token para interagir com o GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Esta etapa 'git push' é geralmente desnecessária.
      # O plugin '@semantic-release/github' (comum no semantic-release)
      # já cuida do push das tags e da criação da release no GitHub.
      # Se as tags não estiverem sendo empurradas após a execução do semantic-release,
      # você pode reconsiderar esta etapa ou ajustar a configuração do semantic-release.
      # - name: Push Final Git Changes (If necessary)
      #   run: |
      #     git push --follow-tags origin main